#!/bin/bash
php "$ROOT_PATH"/jsn.php --array-name=!wrong-name < "$ROOT_PATH"/data/parameters/minimal-json > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The script should report an error - wrong name of XML element!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output
fi

exit $RET_VAL
