#!/bin/bash
php "$ROOT_PATH"/jsn.php --input= < "$ROOT_PATH"/minimal-json > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The script run even when the input file was not properly specified!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output
fi


exit $RET_VAL
