#!/bin/bash
echo "{ \"output\" : \"test\" }" | php "$ROOT_PATH"/jsn.php > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should proceed correctly with simple JSON file!"
else
  echo "OK"
fi

if [[ -s script-output ]]; then
  rm script-output
else
  echo "The script has no output!"
fi

exit $RET_VAL
