#!/bin/bash

if [[ "$(hostname)" == "merlin.fit.vutbr.cz" ]]; then
  php "$ROOT_PATH"/jsn.php --output=/etc/shadow  < "$ROOT_PATH"/minimal-json > script-output
else
  php "$ROOT_PATH"/jsn.php --output="$ROOT_PATH"/unwriteable-file  < "$ROOT_PATH"/minimal-json > script-output
fi

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The script run even when the output file was not writeable!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output
fi

exit $RET_VAL
