#!/bin/bash
php "$ROOT_PATH"/jsn.php --output="$ROOT_PATH"/unwriteable-file < /dev/null > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The script run even when the output file was not writeable!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
fi

rm -f script-output

exit $RET_VAL
