#!/bin/bash
php "$ROOT_PATH"/jsn.php --output="$(pwd)"/filename < "$ROOT_PATH"/data/parameters/minimal-json

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should work properly with absolute paths!"
else
  echo "OK"
fi

if [[ -s "$(pwd)/filename" ]]; then
  rm -f "$(pwd)/filename"
else
  echo "The script didn't handle the absolute path for --output parameter!"
fi

exit $RET_VAL
