#!/bin/bash
php "$ROOT_PATH"/jsn.php --input="$ROOT_PATH"/data/parameters/cp1250-file > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The script runs even when the input file has wrong format!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output
fi

exit $RET_VAL
