#!/bin/bash

if [[ "$ROOT_PATH" == "" ]]; then
  echo "The \$ROOT_PATH shell variable is not set!"
  exit 3
fi


rm -f "$ROOT_PATH/data/parameters/unreadable-file" || {
  echo "Could not remove previous 'unreadable-file'"
  exit 4
}

rm -f "$ROOT_PATH/data/parameters/unwriteable-file" || {
  echo "Could not remove previous 'unwriteable-file'"
  exit 4
}

touch "$ROOT_PATH/data/parameters/unreadable-file"
touch "$ROOT_PATH/data/parameters/unwriteable-file"


chmod 0000 "$ROOT_PATH/data/parameters/unreadable-file" "$ROOT_PATH/data/parameters/unwriteable-file" || {
  echo "Could not change rights on testsuite files!"
  exit 5
}


if [[ "$(hostname)" == "merlin.fit.vutbr.cz" ]]; then
  typeset IFS_backup=$IFS           # Backup of actual IFS for later restoration.
  IFS=$'\n'                         # New IFS for line operations below.

  cd ../../ || {
    echo "Script could not change into tests directory!"
    exit 6
  }

  for file_path in $(find . -type f -name cmd-given | sort); do
    # Changing 'cmd-given' scripts, so they can run on merlin server:
    {
      sed -i -r -e 's/php "\$ROOT_PATH"\/jsn\.php/php -d open_basedir="" "\$ROOT_PATH"\/jsn.php/g' "$file_path"
    }
    
  done

  IFS=$IFS_backup                   # Restoring IFS.
else
  php < /dev/null

  if [[ $? != 0 ]]; then
    echo "The PHP CLI is probably not installed! Please, double-check it and try again!"
    exit 7
  fi
fi


chmod +x "$ROOT_PATH"/jexamxml.sh
"$ROOT_PATH"/jexamxml.sh "$(pwd)" "" ""


if [[ $? != 2 ]]; then
  echo "The Java CLI is either missing or JExamXML files are corrupted!"
  exit 8
fi

if ! [[ -r "$ROOT_PATH/jsn.php" && -f "$ROOT_PATH/jsn.php" && -s "$ROOT_PATH/jsn.php" ]]; then
  echo "The 'jsn.php' is not present in '\$ROOT_PATH' or is not readable!"
  exit 9
fi


echo "OK"


exit 0
