#!/bin/bash
php "$ROOT_PATH"/jsn.php -l < "$ROOT_PATH"/literals-transform > script-output

RET_VAL=$?

cat "$ROOT_PATH"/XML-header > valid-output

echo "<root>
    <test1><true /></test1>
    <test2><false /></test2>
    <test3><null /></test3>
    <test4>
        <array>
            <item><true /></item>
            <item><false /></item>
            <item><null /></item>
        </array>
    </test4>
</root>" >> valid-output

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should process this input without any error!"
else
  # NOTE: We're injecting <root> & </root> elements so the JExamXML will not
  #       report an error that the XML is not well-formed.
  cat "$ROOT_PATH"/XML-header > script-output.tmp
  echo "<root>" >> script-output.tmp
  tail -n +2 script-output >> script-output.tmp
  cat script-output.tmp > script-output
  echo "</root>" >> script-output
  
  rm -f script-output.tmp

  "$ROOT_PATH"/jexamxml.sh "$(pwd)" valid-output script-output

  if [[ $? != 0 ]]; then
    echo "Wrong output format for -l parameter! See the delta.xml file."
  else
    rm -f valid-output script-output delta.xml
    echo "OK"
  fi
fi

exit $RET_VAL

