#!/bin/bash
php "$ROOT_PATH"/jsn.php -a < "$ROOT_PATH"/array > script-output

RET_VAL=$?

cat "$ROOT_PATH"/XML-header > valid-output

echo "<root>
    <array size=\"11\">
        <item value=\"42\" />
        <item value=\"69\" />
        <item value=\"141\" />
        <item value=\"192\" />
        <item value=\"256\" />
        <item value=\"512\" />
        <item value=\"1024\" />
        <item value=\"2048\" />
        <item value=\"8192\" />
        <item value=\"16384\" />
        <item value=\"32768\" />
    </array>
</root>" >> valid-output

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should process this input without any error!"
else
  # NOTE: We're injecting <root> & </root> elements so the JExamXML will not
  #       report an error that the XML is not well-formed.
  cat "$ROOT_PATH"/XML-header > script-output.tmp
  echo "<root>" >> script-output.tmp
  tail -n +2 script-output >> script-output.tmp
  cat script-output.tmp > script-output
  echo "</root>" >> script-output
  
  rm -f script-output.tmp

  "$ROOT_PATH"/jexamxml.sh "$(pwd)" valid-output script-output

  if [[ $? != 0 ]]; then
    echo "Wrong output format for -a parameter! See the delta.xml file."
  else
    rm -f valid-output script-output delta.xml
    echo "OK"
  fi
fi

exit $RET_VAL

