#!/bin/bash
php "$ROOT_PATH"/jsn.php -h=! < "$ROOT_PATH"/data/parameters/subst-file > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The script didn't recongnized invalid name of XML element for -h parameter after substitution!"
fi

diff -upwB script-output "$ROOT_PATH"/data/parameters/XML-header > delta

if [[ -s delta ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output delta
fi

exit $RET_VAL

