#!/bin/bash
php "$ROOT_PATH"/jsn.php --help --help > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "Duplication of parameters is not allowed!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
fi

rm -f script-output

exit $RET_VAL
