#!/bin/bash
php "$ROOT_PATH"/jsn.php --input="$ROOT_PATH"/cp1250-file --input="$ROOT_PATH"/utf8-file > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The duplication of parameters is not allowed!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output
fi

exit $RET_VAL

