#!/bin/bash
php "$ROOT_PATH"/jsn.php --start=42 -t < "$ROOT_PATH"/data/parameters/array > script-output

RET_VAL=$?

cat "$ROOT_PATH"/data/parameters/XML-header > valid-output

echo "<root>
    <array>
        <item index=\"42\" value=\"42\" />
        <item index=\"43\" value=\"69\" />
        <item index=\"44\" value=\"141\" />
        <item index=\"45\" value=\"192\" />
        <item index=\"46\" value=\"256\" />
        <item index=\"47\" value=\"512\" />
        <item index=\"48\" value=\"1024\" />
        <item index=\"49\" value=\"2048\" />
        <item index=\"50\" value=\"8192\" />
        <item index=\"51\" value=\"16384\" />
        <item index=\"52\" value=\"32768\" />
    </array>
</root>" >> valid-output

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should process this input without any error!"
else
  # NOTE: We're injecting <root> & </root> elements so the JExamXML will not
  #       report an error that the XML is not well-formed.
  cat "$ROOT_PATH"/data/parameters/XML-header > script-output.tmp
  echo "<root>" >> script-output.tmp
  tail -n +2 script-output >> script-output.tmp
  cat script-output.tmp > script-output
  echo "</root>" >> script-output
  
  rm -f script-output.tmp

  "$ROOT_PATH"/jexamxml.sh "$(pwd)" valid-output script-output

  if [[ $? != 0 ]]; then
    echo "Wrong output format for --start=42 -t parameters! See the delta.xml file."
  else
    rm -f valid-output script-output delta.xml
    echo "OK"
  fi
fi

exit $RET_VAL
