#!/bin/bash
php "$ROOT_PATH"/jsn.php --start=10.99 -t < "$ROOT_PATH"/data/parameters/minimal-json > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "The script run even when the float value for --start was supplied!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output
fi

exit $RET_VAL

