#!/bin/bash
php "$ROOT_PATH"/jsn.php -s < "$ROOT_PATH"/string-transform > script-output

RET_VAL=$?

cat "$ROOT_PATH"/XML-header > valid_1
cat "$ROOT_PATH"/XML-header > valid_2

echo "<test1>string</test1>
<test2>
    <array>
        <item>string</item>
    </array>
</test2>" >> valid_1

echo "<test1>
    string
</test1>
<test2>
    <array>
        <item>
            string
        </item>
    </array>
</test2>" >> valid_2


if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should process this input without any error!"
else
  diff -upwB script-output valid_1 > delta_1
  diff -upwB script-output valid_2 > delta_2

  if [[ -s delta_1 && -s delta_2 ]]; then
    echo "Wrong output format for -s parameter!"
  else
    echo "OK"
  fi
fi

rm -f script-output valid_1 valid_2 delta_1 delta_2

exit $RET_VAL


