#!/bin/bash
php "$ROOT_PATH"/jsn.php -r=root-element < "$ROOT_PATH"/minimal-json > script-output

RET_VAL=$?

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<root-element />" > correct-output

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should proceed correctly with the root element"
elif ! [[ -s script-output ]]; then
  echo "The script has no output!"
else
  "$ROOT_PATH"/jexamxml.sh "$(pwd)" correct-output script-output

  if [[ $? != 0 ]]; then
    echo "Wrong output for -r=root-element! See the delta.xml file."
  else
    rm -f correct-output script-output delta.xml
    echo "OK"
  fi
fi

exit $RET_VAL
