#!/bin/bash
php "$ROOT_PATH"/jsn.php -r=root-element < /dev/null > script-output

RET_VAL=$?

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<root-element />" > correct-output_1
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<root-element>
</root-element>" > correct-output_2


if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should proceed correctly with the root element"
elif ! [[ -s script-output ]]; then
  echo "The script has no output!"
else 
  diff -upwB correct-output_1 script-captured > delta_1 2>/dev/null
  diff -upwB correct-output_2 script-captured > delta_2 2>/dev/null

  if [[ -s delta_1 && -s delta_2 ]]; then
    echo "Wrong output for -r=root-element!"
  else
    echo "OK"
  fi
fi

rm -f correct-output_1 correct-output_2 delta_1 delta_2 script-output

exit $RET_VAL
