#!/bin/bash
php "$ROOT_PATH"/jsn.php --help -n < "$ROOT_PATH"/minimal-json > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "OK"
else
  echo "Combination of --help & other parameters is not allowed!"
fi

if [[ -s script-output ]]; then
  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
else
  rm -f script-output
fi


exit $RET_VAL
