#!/bin/bash
php "$ROOT_PATH"/jsn.php --input=../../../utf8-file > script-output

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should proceed correctly with the relative path!"
else
  echo "OK"
fi

if [[ -s script-output ]]; then
  rm -f script-output
else
  echo "The script has no output!"
fi

exit $RET_VAL
