#!/bin/bash
php "$ROOT_PATH"/jsn.php --output=../../../data/parameters/filename < "$ROOT_PATH"/data/parameters/minimal-json

RET_VAL=$?

if [[ $RET_VAL -gt 0 ]]; then
  echo "The script should work properly with relative paths!"
else
  echo "OK"
fi

if [[ -s "$ROOT_PATH/data/parameters/filename" ]]; then
  rm -f "$ROOT_PATH/data/parameters/filename"
else
  echo "The script didn't handle the relative path for --output parameter!"
fi

exit $RET_VAL
